name: Python Tests with Coverage and Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # 僅檢查語法錯誤和未定義的名稱
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # 完整的 style 檢查（可選，寬鬆設置）
        flake8 . --count --max-complexity=10 --max-line-length=120 --statistics
    
    - name: Run tests with coverage
      run: |
        coverage run --source=. CalcTest.py
        coverage report -m
        coverage xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true